version: "3.8"

services:
  producer:
    build:
      context: ./service1
    container_name: producer
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped

  consumer:
    build:
      context: ./service2
    container_name: consumer
    env_file:
      - .env
    volumes:
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped
